schedsim:
	gcc -std=c11 -I ./libs schedsim.c -o schedsim 

schedgen:  
	gcc -std=c11 -o schedgen schedgen.c

schedstats:
	gcc -std=c11 -I ./libs schedstats.c -o schedstats 
clean:
	rm -f schedsim
	rm -f schedgen


